#ifndef TARGETCONDITIONALS_H
#define TARGETCONDITIONALS_H
#define TARGET_OS_MAC 1
#define TARGET_OS_IPHONE 1
#define TARGET_OS_EMBEDDED 1
#define TARGET_OS_WIN32 0
#define TARGET_OS_UNIX 1
#define TARGET_CPU_ARM 1
#define TARGET_CPU_ARM32 1
#define TARGET_CPU_X86 0
#define TARGET_CPU_X86_64 0
#define TARGET_CPU_PPC 0
#define TARGET_RT_LITTLE_ENDIAN 1
#define TARGET_RT_BIG_ENDIAN 0
#endif
